### ISSUE TITLE
MS Project Update

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2-c126#20]
Update MapStore downstream project to the last stable version 2020.01.xx. Align the list of enabled plugins with the one provided in the stable branch.

**Comment by MV88** [comment]
@giacomoc92 i have uploaded the war [here](http://demo.geo-solutions.it/share/goldcorp/)

**Comment by giacomoc92** [comment]
@tdipisa is this finished? can I use it?

**Comment by tdipisa** [comment]
@giacomoc92 yes
