### ISSUE TITLE
MapStore / GeoServer Update

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2-c126#21]
**MapStore**
Update MS to the latest uptade provided with #20 

**GeoServer**
Update the GeoServer instance to the last stable (2.16.3 is probably better now)

There isn't a document that collects the installed GS plugins, therefore we have to check. Of course the following plugins are needed for MS:

- wps
- authkey
- querylayer

then:

- oracle? to check

The client environment is quite simple at the moment. There are two tomcat instances in the same machine for GeoServer: one used for production and one, usually turned off, to test the GS update before moving it to the production instance.

**Comment by giacomoc92** [comment]
I have taken a look at the lib directory and compared it to a clean deploy on my machine (used the same geoserver version)

Plugins:

- authkey-plugin
- control-flow-plugin
- css-plugin
- monitor-plugin
- querylayer-plugin
- wps-plugin

**Comment by tdipisa** [comment]
Good @giacomoc92, please keep the documentatin updated with these. thank you

**Comment by giacomoc92** [comment]
The new geoserver and mapstore are deployed and the documentation updated.

I still need to conclude testing as for me it's still not clear how the authkey should be working here. We will conclude this on Wednesday
