### ISSUE TITLE
MapStore / GeoServer Production Deploy Update

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2-c126#26]
see description on #21

To take into account [this](https://github.com/geosolutions-it/support/issues/686#issuecomment-653570054) for the deploy in production

**Comment by giacomoc92** [comment]
While testing some problems emerged with the ELDAP configuration. Some users should be able to log in mapstore and see every layer, but they only see a small part instead.
While we wait feedback from the customer, this is blocked.

**Comment by randomorder** [comment]
we're still waiting for the green light frm the client to move on with this, right @tdipisa ?

**Comment by tdipisa** [comment]
@randomorder we have the go, see the the comments [here](https://github.com/geosolutions-it/support/issues/686#issuecomment-653414494)

**Comment by tdipisa** [comment]
To take into account [this](https://github.com/geosolutions-it/support/issues/686#issuecomment-653570054) for the deploy in production

**Comment by Gnafu** [comment]
TODO:
- [ ] Keep the existing PROD configuration
- [ ] Update GeoServer and MapStore with the same versions that are on TEST

**Comment by randomorder** [comment]
@tdipisa can you communicate to the client that @Gnafu will perform this on Monday morning (italy)?

**Comment by tdipisa** [comment]
@Gnafu I think that for MS we can use the same war file used for test, you just need to align the MS config to use the production GS.

**Comment by Gnafu** [comment]
GS and MS2 deployed.
MS2 is missing some translations for the stories button, should they be active?
