### ISSUE TITLE
Missing translations in root folder 

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/MapStore2-c126#4]
If translations are missing from root folder some pages or plugins don't work.

### Cookie plugin
- Missing folder with translation `/translations/fragment` (check pom.xml)
- Verify if translation path is configurable or hardcoded, currently it searches translations folder in root

## Embedded
- currently it searches translations folder in root, this happens because `embedded.js` is build from submodule folder and in that case MapStore2 retrieves translations from the root folder

**Comment by MV88** [comment]
### The cookie plugin
has hardcoded a relative path which needs to be changed when mapstore is used as submodule

### embedded 
was using the wrong translationsPath, only `./translations` 
we should point by default to the translations present in the submodule
